services:
  web:
    build:
      context: .
      target: backend-development
      # Platforms need to be specified for the build to work on Apple Silicon Macs.
      platforms:
        - linux/amd64
    command: ["tail", "-f", "/dev/null"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/data
      # Named volume to prevent the static assets build during image build from being overriden by the above project root bind mount.
      - frontend_assets:/app/lpld/static/comp:ro
  frontend:
    build:
      context: .
      target: frontend
      # Platforms need to be specified for the build to work on Apple Silicon Macs.
      platforms:
        - linux/amd64
    command: ["tail", "-f", "/dev/null"]
    env_file:
      - .env
    volumes:
      - .:/home/node/app
      # Named volume to prevent the static assets build during image build from being overriden by the above project root bind mount.
      - frontend_assets:/home/node/app/lpld/static/comp:rw
      # Anonymous volume to prevent the node_modules directory being overridden by the above bind mounting for the project root.
      - /home/node/app/node_modules

volumes:
  frontend_assets:
