services:
  web:
    image: lpld_web
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/data
    env_file: .env
    environment:
      SECRET_KEY: thisisnotasecrectkey
      DEBUG: "True"
      INTERNAL_IPS: "172.20.0.1"
      PORT: 8000
    command: ["tail", "-f", "/dev/null"]
