services:
  web:
    build:
      context: .
      target: backend
    command: ["tail", "-f", "/dev/null"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/data
  frontend:
    build:
      context: .
      target: frontend
    command: ["tail", "-f", "/dev/null"]
    env_file:
      - .env
    volumes:
      - .:/home/node/app
      # Anonymous volume to prevent the node_modules directory being overridden by the above mounting for the project root.
      - /home/node/app/node_modules
