services:
  web:
    image: lpld_web
    build: .
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "thisisnotasecrectkey"
      DB_DIR: "/data"
      USE_SQLITE: "true"
    command: ["tail", "-f", "/dev/null"]
