services:
  web:
    image: lpld_web
    build:
      context: .
      target: backend-development
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "thisisnotasecrectkey"
    command: ["tail", "-f", "/dev/null"]
  frontend:
    build:
      context: .
      target: frontend
    command: ["tail", "-f", "/dev/null"]
