services:
  web:
    image: lpld_web
    build: .
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/data

  db:
    image: "postgres:13"
    expose:
      - 5432
    volumes:
      - ./dbdump:/dbdump
    environment:
      POSTGRES_USER: lpld
      POSTGRES_PASSWORD: lpld
