# Generated by Django 4.0.8 on 2022-11-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("technologies", "0001_initial"),
        ("core", "0002_project_tech_relation"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO technologies_technology (
                    id,
                    name
                )
                SELECT
                    id,
                    name
                FROM
                    core_technology;
            """,
            reverse_sql="""
                INSERT INTO core_technology (
                    id,
                    name
                )
                SELECT
                    id,
                    name
                FROM
                    technologies_technology;
            """,
        )
    ]
