# Generated by Django 4.0.8 on 2022-11-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("technologies", "0002_copy_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technology",
            options={"ordering": ["name"], "verbose_name_plural": "Technologies"},
        ),
    ]
