# Generated by Django 4.1.7 on 2023-05-27 04:10

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(blank=True, max_length=500),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "markdown",
                                wagtailmarkdown.blocks.MarkdownBlock(
                                    template="organisms/prose/prose-markdown-block.html"
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
