# Generated by Django 4.1.7 on 2023-04-07 02:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("markdown", wagtailmarkdown.blocks.MarkdownBlock()),
                    (
                        "heading",
                        wagtail.blocks.StructBlock(
                            [("text", wagtail.blocks.CharBlock(required=True))]
                        ),
                    ),
                    (
                        "subheading",
                        wagtail.blocks.StructBlock(
                            [("text", wagtail.blocks.CharBlock(required=True))]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
