# Generated by Django 4.1.7 on 2023-04-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blogpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="introduction",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
