# Generated by Django 4.1.7 on 2023-04-13 01:30

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blogpage_introduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="introduction",
            field=wagtail.fields.RichTextField(blank=True, max_length=500),
        ),
    ]
