# Generated by Django 4.1.7 on 2023-04-13 01:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("blog", "0005_alter_blogpage_introduction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPage",
            new_name="BlogPostPage",
        ),
    ]
