# Generated by Django 4.0.4 on 2022-04-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("projects", "0002_project_tech_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.customimage",
            ),
        ),
    ]
