# Generated by Django 4.1.13 on 2024-07-18 03:57

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexpage",
            name="introduction",
            field=wagtail.fields.RichTextField(blank=True, max_length=500),
        ),
    ]
