# Generated by Django 4.0.4 on 2022-04-28 01:20

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="introduction",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
