# Generated by Django 4.0.4 on 2022-05-01 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("home", "0002_homepage_introduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="profile_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.customimage",
            ),
        ),
    ]
