# Generated by Django 4.0.8 on 2022-11-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_project_tech_relation"),
        ("technologies", "0003_alter_technology_options"),
        ("projects", "0005_alter_projecttechnologyrelation_technology"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Technology",
        ),
    ]
