# Generated by Django 4.0.8 on 2022-11-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_tech_relation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
