# https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
name: continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Restore Docker layers from branch
        if: ${{ github.event_name == 'push' }}
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.ref_name }}

      - name: Restore Docker layers from branch or target
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.head_ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.base_ref }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          load: true
          tags: lpld_web:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: List images
        run: docker images

      - name: Start docker stack
        run: docker-compose -f docker-compose.ci.yaml up --detach

      - name: Check for missing migrations
        run: docker-compose -f docker-compose.ci.yaml exec -T web python manage.py makemigrations --dry-run --check

      - name: Run black
        run: docker-compose -f docker-compose.ci.yaml exec -T web black . --check

      - name: Run isort
        run: docker-compose -f docker-compose.ci.yaml exec -T web isort . --check

      - name: Run flake8
        run: docker-compose -f docker-compose.ci.yaml exec -T web flake8

      - name: Run mypy
        run: docker-compose -f docker-compose.ci.yaml exec -T web mypy .

      - name: Run pytest
        run: docker-compose -f docker-compose.ci.yaml exec -T web pytest

      - name: Run standard.js
        run: docker-compose -f docker-compose.ci.yaml exec -T frontend npm run standard

      - name: Stop docker stack
        run: docker-compose -f docker-compose.ci.yaml stop

        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Save (move) new cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
