# https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
name: ci (sequential)

on: [push]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: lpld_web:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: List images
        run: docker images

      - name: Start docker stack
        run: docker-compose -f docker-compose.ci.yml up --detach

      - name: Run black
        run: docker-compose -f docker-compose.ci.yml exec -T web black . --check

      - name: Run isort
        run: docker-compose -f docker-compose.ci.yml exec -T web isort . --check

      - name: Run flake8
        run: docker-compose -f docker-compose.ci.yml exec -T web flake8

      - name: Run mypy
        run: docker-compose -f docker-compose.ci.yml exec -T web mypy .

      - name: Run pytest
        run: docker-compose -f docker-compose.ci.yml exec -T web pytest

      - name: Stop docker stack
        run: docker-compose -f docker-compose.ci.yml stop
