# https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: lpld_web:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          outputs: type=docker,dest=/tmp/lpld-image.tar

      - name: List images
        run: docker images

        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lpld-image
          path: /tmp/lpld-image.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # This is the a separate action that sets up buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: lpld-image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/lpld-image.tar
          docker image ls -a

      - name: Start docker stack
        run: docker-compose -f docker-compose.ci.yaml up --no-build --detach

      - name: Run test
        run: |
          docker-compose -f docker-compose.ci.yaml exec -T web pytest

      - name: Stop docker stack
        run: docker-compose -f docker-compose.ci.yaml stop

  black:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # this is the a separate action that sets up buildx runner
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: lpld-image
          path: /tmp

      - name: load image
        run: |
          docker load --input /tmp/lpld-image.tar
          docker image ls -a

      - name: start docker stack
        run: docker-compose -f docker-compose.ci.yaml up --no-build --detach

      - name: run black
        run: |
          docker-compose -f docker-compose.ci.yaml exec -T web black . --check

      - name: stop docker stack
        run: docker-compose -f docker-compose.ci.yaml stop

  isort:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # this is the a separate action that sets up buildx runner
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: lpld-image
          path: /tmp

      - name: load image
        run: |
          docker load --input /tmp/lpld-image.tar
          docker image ls -a

      - name: start docker stack
        run: docker-compose -f docker-compose.ci.yaml up --no-build --detach

      - name: run isort
        run: docker-compose -f docker-compose.ci.yaml exec -T web isort . --check

      - name: stop docker stack
        run: docker-compose -f docker-compose.ci.yaml stop

  flake8:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # this is the a separate action that sets up buildx runner
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: lpld-image
          path: /tmp

      - name: load image
        run: |
          docker load --input /tmp/lpld-image.tar
          docker image ls -a

      - name: start docker stack
        run: docker-compose -f docker-compose.ci.yaml up --no-build --detach

      - name: run flake8
        run: docker-compose -f docker-compose.ci.yaml exec -T web flake8

      - name: stop docker stack
        run: docker-compose -f docker-compose.ci.yaml stop

  mypy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # this is the a separate action that sets up buildx runner
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: lpld-image
          path: /tmp

      - name: load image
        run: |
          docker load --input /tmp/lpld-image.tar
          docker image ls -a

      - name: start docker stack
        run: docker-compose -f docker-compose.ci.yaml up --no-build --detach

      - name: run mypy
        run: docker-compose -f docker-compose.ci.yaml exec -T web mypy .

      - name: stop docker stack
        run: docker-compose -f docker-compose.ci.yaml stop

  clean-up:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [test, black, isort, flake8, mypy]
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: lpld-image
